// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/get_manifests/integration.tsx";
import * as $1 from "./routes/get_manifests/production.tsx";
import * as $2 from "./routes/get_manifests/reviewers.tsx";
import * as $3 from "./routes/get_manifests/unbouncers.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/App.tsx";
import * as $$1 from "./islands/AppCheckbox.tsx";

const manifest = {
  routes: {
    "./routes/get_manifests/integration.tsx": $0,
    "./routes/get_manifests/production.tsx": $1,
    "./routes/get_manifests/reviewers.tsx": $2,
    "./routes/get_manifests/unbouncers.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/App.tsx": $$0,
    "./islands/AppCheckbox.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
