export const sampleReviewers =
  '[   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/quote-calculator/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/dynamic-image/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/font-awesome/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/google-maps/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/tag-manager/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/instant-messenger/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/popups-sticky-bars/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/promo-video-maker/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/animated-headings/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/instagram/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/tiktok-embed/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/woo-commerce/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/google-reviews/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/styled-images/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/facebook-share/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/pinterest/manifest.js" ]';
export const sampleProduction =
  '[ "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/font-awesome/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/google-maps/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/tag-manager/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/instant-messenger/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/popups-sticky-bars/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/promo-video-maker/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/animated-headings/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/instagram/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/tiktok-embed/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/woo-commerce/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/google-reviews/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/styled-images/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/facebook-share/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/pinterest/manifest.js" ]';
export const sampleIntegration =
  '[   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/quote-calculator/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/dynamic-image/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/font-awesome/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/google-maps/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/tag-manager/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/instant-messenger/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/popups-sticky-bars/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/promo-video-maker/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/animated-headings/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/instagram/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/tiktok-embed/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/woo-commerce/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/google-reviews/manifest.js",   "https://app-assets-unbounce-com.s3.amazonaws.com/content-smart-builder-apps/app-reviews/styled-images/manifest.js" ]';

export const releasedLocations = [
  "integration",
  "reviewers",
  "unbouncers",
  "production",
];
